In [1]:
!pip install ultralytics
from ultralytics import YOLO
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import cv2

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.5/983.5 kB 11.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 34.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 29.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 31.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 77.5 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstall

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
model = YOLO("yolo11n-pose.pt")

video_path = "/content/drive/MyDrive/DAT255_Semesterproject/pipeline_test_videos/IMG_1208.MOV"

results = model.track(source=video_path, show=True, save=True, stream=True)

video_keypoints = np.ndarray((49, 17, 2))
for i, result in enumerate(results):
    normalized_keypoints = result.keypoints.xyn.cpu().numpy()
    video_keypoints[i] = normalized_keypoints
    result.show()  # display to screen

Output hidden; open in https://colab.research.google.com to view.

In [7]:
print(video_keypoints.shape)

(49, 17, 2)


In [8]:
for i, frame in enumerate(video_keypoints):
  print(frame)

[[    0.43527     0.44811]
 [    0.43037     0.40908]
 [    0.42589     0.45254]
 [     0.4629     0.37048]
 [          0           0]
 [    0.55146       0.367]
 [    0.54773     0.62298]
 [    0.69181     0.25216]
 [    0.66169     0.77887]
 [     0.7989      0.2362]
 [     0.6405     0.71214]
 [    0.79253      0.4412]
 [    0.78518     0.56533]
 [    0.86591     0.57521]
 [    0.87165     0.72852]
 [    0.97176      0.4914]
 [    0.96798     0.60493]]
[[     0.4325      0.4653]
 [    0.42681     0.43085]
 [          0           0]
 [    0.45521     0.38053]
 [          0           0]
 [    0.53455     0.34345]
 [    0.53877     0.54741]
 [    0.67275     0.26601]
 [    0.63669     0.68993]
 [    0.82092     0.24457]
 [    0.66738     0.70708]
 [    0.77183     0.43512]
 [    0.77028     0.54918]
 [     0.8645     0.57552]
 [    0.88623     0.71126]
 [     0.9666     0.55222]
 [    0.97291     0.66237]]
[[     0.4435     0.46313]
 [    0.43618     0.42462]
 [    0.43171     0.46974]

In [10]:
x = np.zeros((49, 34))

In [11]:
for i, frame in enumerate(video_keypoints):
  for j, keypoint in enumerate(frame):
    x[i][j*2] = keypoint[0]
    x[i][j*2+1] = keypoint[1]

In [12]:
print(x)

[[    0.43527     0.44811     0.43037 ...      0.4914     0.96798     0.60493]
 [     0.4325      0.4653     0.42681 ...     0.55222     0.97291     0.66237]
 [     0.4435     0.46313     0.43618 ...     0.54075     0.96582     0.67749]
 ...
 [    0.44516     0.44151     0.43733 ...           0           0           0]
 [    0.44521     0.43305     0.43774 ...           0           0           0]
 [    0.44808     0.43874     0.44288 ...           0           0           0]]


In [13]:
np.save("/content/drive/MyDrive/DAT255_Semesterproject/processed_data/za_neih_waving_one_arm.npy", x)